### ISSUE TITLE
Add Windows support for CRDS client

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/crds#790]
Currently crds client to request bestrefs does not work on the Windows platform.  See the involved traceback here:

https://travis-ci.org/github/spacetelescope/jwst/jobs/692695855#L755

This is a blocker of https://github.com/spacetelescope/jwst/issues/4996 

See also https://github.com/spacetelescope/jwst/pull/5578

**Comment by alphasentaurii** [comment]
Resolved in CRDS [11.16.7](https://github.com/spacetelescope/crds/releases/tag/11.16.7)

**Comment by jdavies-st** [comment]
Resolved by #891

**Comment by pllim** [comment]
What does this mean? Is `jwst` compatible with Windows now?

**Comment by jdavies-st** [comment]
No, it is not.  There's still some C code in `jwst` that is not Windows compatible.  See

https://github.com/jdavies-st/jwst/actions/runs/3123743757/jobs/5066598065

Back when this issue was written, `jwst` package was fine and `crds` was the hangup.  Now `crds` seems fine, and new C code added to `jwst` since then has made `jwst` break.  This is why there needs to be a Windows CI job in `jwst` once things get working.
